// Generated by LOKIN commerce schema dependency scanner.
export const COMMERCE_SCHEMA_MANIFEST = [
  {
    "name": "CommerceAIAction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAbandonedCheckout",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAddressIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAdminNotification",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAlertSubscription",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAudit",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAudit2",
    "isCore": false,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceAuditLog",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceAutomationCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAutomationLog",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAutomationRule",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceAutomationState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCampaignAttribution",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCancellation",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCartEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCatalogCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCatalogHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCatalogSync",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCheckoutEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCommand",
    "isCore": true,
    "directReferenceCount": 4,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 3
      }
    ]
  },
  {
    "name": "CommerceCommandResult",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceConversionCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceConversionSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCostSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerAlert",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerConsent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerExperienceScore",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerJourney",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerMessage",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerPreference",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerPromise",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerRecovery",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerSatisfaction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerSegment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerStatus",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceCustomerTimeline",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDailyDigest",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDashboardPreference",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDataQualityIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDataRetention",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDeadLetter",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceDeliveryEstimate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDeliveryProof",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDeliveryRisk",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceDeliveryWindow",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceEscalation",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceException",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceExceptionCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceExceptionRule",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceExperiment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceExperimentResult",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFeatureFlag",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFinancialCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFraudReview",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentDecision",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentEstimate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentItem",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentPerformance",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentPolicy",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceFulfillmentQueue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceIncident",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceIncidentEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceInsight",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceInsightEngineState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceInsightFeedback",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceIntelligenceCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceInventoryAlert",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceJobRun",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceKPI",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceLoyaltySignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceMarginAlert",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceMessageTemplate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceMessagingCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceMessagingSync",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNextBestAction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNotification",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNotificationEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNotificationPolicy",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNotificationPreference",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceNotificationQueue",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceNotificationSuppression",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsAlert",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsAnomaly",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsCapacity",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsDigestSubscriber",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsForecast",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsHeartbeat",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsNote",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsObjective",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsObjectiveHistory",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsPreference",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsRunbook",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsScore",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsSession",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsSummary",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOpsTask",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderAction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderCommunicationState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderForecast",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderItemSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderMilestone",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderNotificationPlan",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderProfit",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderResolution",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderSnapshot",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceOrderSource",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderStateMachine",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderSync",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderSyncState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderTag",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceOrderTimeline",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommercePayoutSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommercePinnedOrder",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommercePriceSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommercePrivacyRequest",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProductMapping",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "CommerceProductPerformance",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProfitGoal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProfitGoalProgress",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderCapability",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderCost",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderCredentialStatus",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderIncident",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderLatency",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderMappingIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderOrderLink",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderRateLimit",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderRouting",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderSLA",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderShippingRate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceProviderSync",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRecommendation",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceReconciliation",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceReconciliationIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRecoveryAction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRefundSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceReprint",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceReturn",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRevenueForecast",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRevenueGoalProgress",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceReviewRequest",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceRiskSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSLA",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSavedView",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSearchHistory",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceServiceLevelPolicy",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShipment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShipmentException",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShipmentLeg",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShippingCostSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShippingCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShippingPerformance",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceShippingPolicy",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceStorefrontEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSupportCase",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSyncCursor",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSyncJob",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSyncLock",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSystemConfig",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSystemEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceSystemHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceTaxSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceTrackingCheckpoint",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceTrackingMessage",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceTrackingSubscription",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceTrackingSync",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceVersionState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "CommerceWebhookReceipt",
    "isCore": true,
    "directReferenceCount": 3,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 2
      }
    ]
  },
  {
    "name": "IntegrationHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCheckoutHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAction",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAlert",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAlertRule",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceArchitecture",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceArchitectureState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAuditTrail",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAutomationMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAutomationState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceAvailabilityMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceBenchmark",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceBrandMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceBrandState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceBuild",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCacheState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCapability",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCatalogLink",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCheckoutMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCheckoutSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCheckoutState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceConfig",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceConnectionState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceControl",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceConversion",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCoreVersion",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommerceCostSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCounter",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceCustomerSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDataQuality",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDataState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDecision",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDeliveryEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDependency",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDeployment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceDiagnostic",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEcosystemMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEcosystemState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEngineState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceError",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceErrorMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEvolution",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceEvolutionLog",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceExperienceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceExperiment",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFeature",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFeedback",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFlag",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFulfillmentLink",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFulfillmentMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFulfillmentSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceFulfillmentState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceGuardrail",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceHealthCheck",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceHeartbeat",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceIncident",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceInsight",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceIntegrationMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceIntegrity",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceIntelligence",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceIntelligenceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceInventorySignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceJob",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceJourney",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceKPI",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceLatencyMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceLifecycle",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceMarginSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceMilestone",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceMonitor",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceNote",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceNotification",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceObjective",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOpsMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOpsSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOpsState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOptimization",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOptimizationState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOrchestration",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOrderMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceOrderState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePerfBudget",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePerfectionGate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePerformance",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePerformanceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePipelineState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePolicy",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommercePolishLog",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePolishState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePreference",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommercePriceSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceProbe",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceProductMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceProvider",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceProviderHealth",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommerceQualityGate",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceQueue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceReadiness",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRecommendation",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRecovery",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRegistry",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommerceRelease",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceReliabilityState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceResourceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRevenueSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRoadmap",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRollup",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRun",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceRuntime",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSLA",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSchemaVersion",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSecurityEvent",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommerceServiceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceStatus",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceStoreMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSummary",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSyncIssue",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSyncLog",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSyncMap",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSyncSignal",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSystemEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSystemScore",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceSystemState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceTelemetry",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceTestResult",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceTimeline",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceTrace",
    "isCore": true,
    "directReferenceCount": 2,
    "references": [
      {
        "path": "base44/shared/commerceModelRegistry.ts",
        "count": 1
      },
      {
        "path": "docs/COMMERCE_MODEL_CONSOLIDATION.md",
        "count": 1
      }
    ]
  },
  {
    "name": "LokinCommerceTrackingState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceUXMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceUXState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceVersion",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceVisualMetric",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceVisualState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceVisualToken",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinCommerceWatch",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinDeliveryStatus",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinFulfillmentEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinFulfillmentSnapshot",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinOrderHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinOrderLink",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinOrderTimeline",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinProductLink",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinProductPerformance",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinProductSyncState",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinProductView",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinStorefrontHealth",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinSystemPulse",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  },
  {
    "name": "LokinTrackingEvent",
    "isCore": false,
    "directReferenceCount": 0,
    "references": []
  }
] as const;
