import React from "react";
import { Link } from "react-router-dom";

export default function Privacy() {
  return <main className="min-h-screen bg-background text-foreground px-5 py-10"><div className="mx-auto max-w-2xl space-y-5">
    <h1 className="text-3xl font-bold">LOKIN AI Privacy Policy</h1><p className="text-sm text-muted-foreground">Last updated: August 19, 2026</p>
    <p>LOKIN AI provides driver productivity, routing, earnings, safety, support, commerce-related tools, and optional AI assistance. This policy explains the categories of information the app may process and why.</p>
    <h2 className="text-xl font-semibold">Information and device features</h2><p>Depending on the features you choose to use, LOKIN AI may process account and contact information, location and route information, delivery and earnings information, vehicle information, support messages, commerce activity, and information you submit in forms. Features may request access to device capabilities such as location, microphone, camera, or files only when needed for a feature you activate.</p>
    <h2 className="text-xl font-semibold">AI processing and your permission</h2><p>Optional LOKIN AI features may send your prompt and the minimum context needed to answer it to LOKIN's configured third-party AI service provider. LOKIN asks for explicit permission before enabling this external AI processing. If you decline, core non-AI features remain available. Do not submit payment-card numbers, government identification numbers, or other unnecessary sensitive information in AI prompts.</p>
    <h2 className="text-xl font-semibold">How information is used</h2><p>Information is used to provide requested app functions, authenticate accounts, personalize driver tools, improve reliability and safety, respond to support requests, process authorized transactions where legally enabled, prevent abuse, and comply with applicable legal or regulatory obligations.</p>
    <h2 className="text-xl font-semibold">Third parties</h2><p>Some features rely on service providers or integrations. Information is shared only as needed to provide a feature the user activates and subject to applicable permissions and provider terms. Regulated commerce, insurance, banking, investing, and similar features remain disabled until the necessary authorized partners, licensing, jurisdiction controls, and production approvals are in place.</p>
    <h2 className="text-xl font-semibold">Your choices</h2><p>You can decline optional device permissions and external AI processing. Some optional features may not work without the permission they require. Account deletion is available from Settings and is designed to remove the LOKIN user account record and associated user-owned app data.</p>
    <h2 className="text-xl font-semibold">Security and retention</h2><p>LOKIN AI uses reasonable technical and organizational safeguards. Information is retained only as needed for the service, security, compliance, dispute resolution, and other legitimate purposes.</p>
    <h2 className="text-xl font-semibold">Contact</h2><p>For privacy, account, billing, safety, or technical questions, use the public LOKIN Support page or signed-in Adaptive AI Support. Human follow-up can be requested when an automated answer is not sufficient.</p>
    <div className="pt-4 flex flex-wrap gap-4 text-sm"><Link className="text-primary hover:underline" to="/support-info">Support</Link><Link className="text-primary hover:underline" to="/terms">Terms of Use</Link><Link className="text-primary hover:underline" to="/login">Return to login</Link></div>
  </div></main>;
}
